version: '4'
services:
# nginx ################################################
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes: # 前端静态资源
      - ./dist/html:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl # 证书
      - ./nginx/common/:/etc/nginx/common # 共用配置
      - ./logs/nginx:/var/log/nginx 
    ports:
      - "8081:8080"
      - "8082:8082"
      - "8083:8083"
      - "8086:8086"
      - "48081:48081"
    privileged: true
    restart: always
    command: nginx -g 'daemon off;'
    
# node ################################################
  node:
    image: node:14-alpine
    container_name: node
    volumes: # 前端静态资源
      - ./logs/pm2:/root/.pm2/logs
    ports:
      - "3000:3000"