# 从官方基础版本构建
FROM php:7.3.7-fpm

# 设置时区
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /var/www
# 官方版本默认安装扩展: 
# Core, ctype, curl
# date, dom
# fileinfo, filter, ftp
# hash
# iconv
# json
# libxml
# mbstring, mysqlnd
# openssl
# pcre, PDO, pdo_sqlite, Phar, posix
# readline, Reflection, session, SimpleXML, sodium, SPL, sqlite3, standard
# tokenizer
# xml, xmlreader, xmlwriter
# zlib

# 验证通过
ARG CHANGE_SOURCE=true
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from deb.debian.org to aliyun source
    sed -i 's/deb.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list && \
    sed -i 's/security-cdn.debian.org/mirrors.aliyun.com/' /etc/apt/sources.list \
;fi

# 验证通过 这里是最最慢的 
RUN apt-get update && apt-get upgrade -y

# bcmath, calendar, exif, gettext, sockets, dba, 
# mysqli, pcntl, pdo_mysql, shmop, sysvmsg, sysvsem, sysvshm 扩展
# 验证通过 慢
# RUN docker-php-ext-install -j$(nproc) bcmath calendar exif gettext sockets dba mysqli pcntl pdo_mysql shmop sysvmsg sysvsem sysvshm iconv
# RUN list --upgradable

# GD 扩展 安装会报错 暂时屏蔽
# RUN apt-get install -y --no-install-recommends libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
# 	&& rm -r /var/lib/apt/lists/* \
#     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#     && docker-php-ext-install -j$(nproc) gd

# imagick 扩展
# RUN export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
#     && apt-get install -y --no-install-recommends libmagickwand-dev \
#     && pecl install imagick-3.4.4 \
#     && docker-php-ext-enable imagick

# # Memcached 扩展 
# RUN apt-get install -y --no-install-recommends libmemcached-dev zlib1g-dev \
#     && pecl install memcached-3.1.3 \
#     && docker-php-ext-enable memcached

# # redis 扩展 验证通过
# RUN pecl install redis-5.0.0 && docker-php-ext-enable redis

# # opcache 扩展  验证通过
# RUN docker-php-ext-configure opcache --enable-opcache && docker-php-ext-install opcache

# xdebug 扩展 验证通过
RUN pecl install xdebug-2.7.2 && docker-php-ext-enable xdebug

# # swoole 扩展 验证通过 慢
# RUN pecl install swoole-4.4.0 && docker-php-ext-enable swoole

# mcrypt 扩展  验证通过
RUN apt-get install -y --no-install-recommends libmcrypt-dev \ 
    && pecl install mcrypt-1.0.2 \
    && docker-php-ext-enable mcrypt
# 镜像信息
LABEL Author="jason"
LABEL Version="2023.1"
LABEL Description="PHP 7.3.7"